// Array con mensajes especiales
const MENSAJES = [
    { emoji: "❤️", texto: "Eres lo mejor que me ha pasado en la vida" },
    { emoji: "💕", texto: "Te amo más cada día que pasa" },
    { emoji: "😊", texto: "Tu sonrisa es mi razón favorita para sonreír" },
    { emoji: "✨", texto: "Contigo quiero construir un futuro hermoso" },
    { emoji: "🌹", texto: "Eres mi persona favorita en todo el mundo" },
    { emoji: "💖", texto: "Gracias por ser la mujer de mis sueños" },
    { emoji: "🎀", texto: "Eres mi tesoro más valioso" },
    { emoji: "💫", texto: "Brillas como las estrellas en la noche" },
    { emoji: "🌟", texto: "Eres la luz de mi vida" },
    { emoji: "💝", texto: "Mi corazón late por ti" },
    { emoji: "🌸", texto: "Eres más hermosa cada día" },
    { emoji: "💗", texto: "Te amo sin condiciones" },
    { emoji: "😍", texto: "Tu belleza me deja sin palabras" },
    { emoji: "🥰", texto: "Eres mi amor eterno" },
    { emoji: "💞", texto: "Juntos somos invencibles" },
    { emoji: "🌺", texto: "Eres la flor más bella del jardín" },
    { emoji: "💓", texto: "Mi corazón es completamente tuyo" },
    { emoji: "🎯", texto: "Eres mi objetivo, mi meta, mi todo" },
    { emoji: "👑", texto: "Eres la reina de mi corazón" },
    { emoji: "🔥", texto: "Tu amor me quema de pasión" },
    { emoji: "⭐", texto: "Eres mi estrella guía" },
    { emoji: "🌙", texto: "Bajo la luna te amaré siempre" },
    { emoji: "☀️", texto: "Eres mi amanecer y mi atardecer" },
    { emoji: "🌈", texto: "Eres todos los colores del arcoíris" },
    { emoji: "💎", texto: "Eres más valiosa que cualquier joya" },
    { emoji: "🎵", texto: "Eres la música de mi alma" },
    { emoji: "🎨", texto: "Eres mi obra de arte favorita" },
    { emoji: "📚", texto: "Eres el libro que quiero leer siempre" },
    { emoji: "✈️", texto: "Contigo viajaría a cualquier lugar" },
    { emoji: "🏝️", texto: "Eres mi paraíso en la tierra" },
    { emoji: "🎁", texto: "Eres el regalo más hermoso que recibí" },
    { emoji: "🍫", texto: "Eres tan dulce como el chocolate" },
    { emoji: "🌻", texto: "Tu sonrisa me ilumina como el sol" },
    { emoji: "🦋", texto: "Eres delicada como una mariposa" },
    { emoji: "🎪", texto: "La vida contigo es una aventura" },
    { emoji: "🎭", texto: "Eres mi obra de teatro favorita" },
    { emoji: "🎸", texto: "Eres la canción que siempre quise escribir" },
    { emoji: "🏆", texto: "Eres mi mayor victoria" },
    { emoji: "🎊", texto: "Cada día contigo es una celebración" },
    { emoji: "💌", texto: "Este corazón es una carta de amor para ti" },
    { emoji: "🌊", texto: "Eres profunda como el océano" },
    { emoji: "⛰️", texto: "Eres fuerte como una montaña" },
    { emoji: "🦁", texto: "Eres valiente y hermosa" },
    { emoji: "🕊️", texto: "Eres paz y tranquilidad" },
    { emoji: "🐚", texto: "Eres rara y hermosa como una perla" },
    { emoji: "🌿", texto: "Eres fresca como una planta nueva" },
    { emoji: "💐", texto: "Eres un ramo de flores perfumadas" },
    { emoji: "🎀", texto: "Eres tan bella como un regalo" },
    { emoji: "🏅", texto: "Eres mi medalla de oro" },
    { emoji: "💍", texto: "Eres la mujer que quiero para siempre" },
    { emoji: "🌙", texto: "Eres mi luna en las noches oscuras" },
    { emoji: "☄️", texto: "Eres mi cometa de deseos" },
    { emoji: "🎆", texto: "Eres fuegos artificiales de alegría" },
    { emoji: "💋", texto: "Tus besos son mi favorito" },
    { emoji: "👀", texto: "Podría mirarte por siempre" },
    { emoji: "👂", texto: "Me encanta escuchar tu voz" },
    { emoji: "💬", texto: "Tus palabras son mi medicina" },
    { emoji: "🤝", texto: "Juntos somos un gran equipo" },
    { emoji: "🎯", texto: "Eres mi único objetivo" },
    { emoji: "🔐", texto: "Eres la llave de mi corazón" },
    { emoji: "🔑", texto: "Eres la solución a mis problemas" },
    { emoji: "⚡", texto: "Tu energía es contagiosa" },
    { emoji: "🌬️", texto: "Eres como una brisa en mi día" },
    { emoji: "❄️", texto: "Eres fría por fuera, caliente por dentro" },
    { emoji: "🔥", texto: "Eres el fuego de mi pasión" },
    { emoji: "💧", texto: "Eres esencial como el agua" },
    { emoji: "🌍", texto: "Eres mi mundo completo" },
    { emoji: "🚀", texto: "Contigo iré al infinito y más allá" },
    { emoji: "🎢", texto: "Contigo la vida es una montaña rusa emocionante" },
    { emoji: "🎡", texto: "Contigo giro como una rueda de la fortuna" },
    { emoji: "🎠", texto: "Eres mi carrusel de felicidad" },
    { emoji: "🏰", texto: "Eres mi castillo de ensueño" },
    { emoji: "🏯", texto: "Eres un templo sagrado para mí" },
    { emoji: "⛪", texto: "Tu amor es lo más sagrado para mí" },
    { emoji: "🕌", texto: "Eres mi oración respondida" },
    { emoji: "🎭", texto: "Eres mi mejor acto" },
    { emoji: "🎪", texto: "La vida es un circo hermoso contigo" },
    { emoji: "🎨", texto: "Eres mi lienzo en blanco" },
    { emoji: "🖼️", texto: "Eres un cuadro de Picasso" },
    { emoji: "📸", texto: "Eres mi foto favorita" },
    { emoji: "📹", texto: "Eres la película de mi vida" },
    { emoji: "📺", texto: "Eres mi serie favorita" },
    { emoji: "📻", texto: "Eres mi estación de radio preferida" },
    { emoji: "📱", texto: "Eres la notificación que siempre quiero recibir" },
    { emoji: "💻", texto: "Eres el programa de mi corazón" },
    { emoji: "⌚", texto: "Eres el tiempo que quiero gastar" },
    { emoji: "📖", texto: "Tu historia es mi libro favorito" },
    { emoji: "✏️", texto: "Eres la tinta de mi pluma" },
    { emoji: "🖊️", texto: "Eres el bolígrafo que escribe mi destino" },
    { emoji: "📝", texto: "Eres el poema de mi vida" },
];
